spring.application.name=apirest
spring.profiles.default=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

app.jwt-secret=${JWT_SECRET}
app.jwt-expiration-ms=${JWT_EXPIRATION_MS:86400000}
