services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwerty
      MYSQL_DATABASE: proyecto
      MYSQL_USERNAME: usuario_proyecto
      MYSQL_PASSWORD: 1234qwerty
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

volumes:
  db_data: